// Mocks generated by Mockito 5.4.6 from annotations
// in customizable_chart/test/viewmodel/chart_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:customizable_chart/model/models/chart_data_model.dart' as _i3;
import 'package:customizable_chart/model/repositories/llm_repository.dart'
    as _i4;
import 'package:customizable_chart/model/services/client/failures/llm_failure.dart'
    as _i6;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChartDataModel_1 extends _i1.SmartFake
    implements _i3.ChartDataModel {
  _FakeChartDataModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LlmRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLlmRepository extends _i1.Mock implements _i4.LlmRepository {
  MockLlmRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.LlmFailure, Map<String, dynamic>>>
  processNaturalLanguagePrompt(String? userInput) =>
      (super.noSuchMethod(
            Invocation.method(#processNaturalLanguagePrompt, [userInput]),
            returnValue: _i5.Future<
              _i2.Either<_i6.LlmFailure, Map<String, dynamic>>
            >.value(
              _FakeEither_0<_i6.LlmFailure, Map<String, dynamic>>(
                this,
                Invocation.method(#processNaturalLanguagePrompt, [userInput]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.LlmFailure, Map<String, dynamic>>>);

  @override
  _i3.ChartDataModel configToChartData(Map<String, dynamic>? config) =>
      (super.noSuchMethod(
            Invocation.method(#configToChartData, [config]),
            returnValue: _FakeChartDataModel_1(
              this,
              Invocation.method(#configToChartData, [config]),
            ),
          )
          as _i3.ChartDataModel);
}
